# Generated by Django 2.1.4 on 2018-12-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idHero', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
