# Generated by Django 2.1.4 on 2018-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunubusApp', '0002_auto_20181214_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLigne', models.CharField(max_length=100)),
                ('compagnie', models.CharField(max_length=100)),
            ],
        ),
    ]
